apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: storm-supervisor-scaledobject
  namespace: storm-cluster
spec:
  scaleTargetRef:
    name: supervisor
    kind: StatefulSet
  minReplicaCount: 1
  maxReplicaCount: 7
  initialCooldownPeriod: 300
  triggers:
    - type: prometheus
      metricType: Value
      metadata:
        serverAddress: http://prometheus.storm-cluster.svc.cluster.local:9090
        metricName: weight_scale
        threshold: "0.75"
        query: weight_scale{ClusterHost="nimbus-ui:8081"}

