apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: storm-supervisor-scaledobject
  namespace: storm-cluster
spec:
  scaleTargetRef:
    name: supervisor
    kind: StatefulSet
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.storm-cluster.svc.cluster.local:9090
        metricName: worker_utilization_ratio
        threshold: "0.7"
        query:
          (worker_cluster_used{ClusterHost="nimbus-ui:8081"})
          /
          (worker_cluster_total{ClusterHost="nimbus-ui:8081"}) # Replace with your actual Prometheus query
