apiVersion: v1
kind: Service
metadata:
  name: storm-exporter
  namespace: storm-cluster
spec:
  selector:
    app: storm-exporter
  type: ClusterIP
  ports:
    - name: port-8082
      port: 8082
      targetPort: 8082