services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks:
      storm_network:
    volumes:
      - ./config/zoo.cfg:/apache-zookeeper-3.9.2-bin/conf/zoo.cfg


  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    volumes:
      - ./config/storm-nimbus.yaml:/conf/storm.yaml
    networks:
      storm_network:
      

  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    volumes:
      - ./config/storm-nimbus.yaml:/conf/storm.yaml
    networks:
      storm_network:

  ui:
    image: storm
    container_name: ui
    command: storm ui
    volumes:
      - ./config/storm-nimbus.yaml:/conf/storm.yaml
    networks:
      storm_network:
    ports:
      - 8081:8081

  storm-exporter:
    image: mr4x2/stormexporter:v1
    container_name: storm-exporter
    environment:
      - STORM_UI_HOST=ui:8081
      - PORT_EXPOSE=8082
      - REFRESH_RATE=5
    networks:
      storm_network:
    ports:
      - 8082:8082
    depends_on:
      - ui
    # TODO: update health check with depend on to avoid fail in run container

# TODO: add log with fluentd to get log from supervisor

networks:
  storm_network:
    driver: bridge
