apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: storm-cluster
spec:
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: storm-cluster
spec:
  selector:
    app: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: storm-cluster
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - name: port-3000
      port: 3000
      targetPort: 3000
      nodePort: 30004
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: storm-cluster
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - name: port-9090
      port: 9090
      targetPort: 9090
      nodePort: 30003