apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: storm-cluster
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - name: port-9090
      port: 9090
      targetPort: 9090
      nodePort: 30003