apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespace: storm-cluster
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: mr4x2/zookeeper-k8s
      ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Pod
metadata:
  name: nimbus
  namespace: storm-cluster
  labels:
    app: nimbus
spec:
  containers:
    - name: nimbus
      image: mr4x2/nimbus-k8s:v2
      ports:
        - containerPort: 8081
        - containerPort: 6627
      resources:
        limits:
          cpu: "1000m"  
          memory: "1Gi"

---
apiVersion: v1
kind: Pod
metadata:
  name: supervisor
  namespace: storm-cluster
  labels:
    app: supervisor
spec:
  containers:
    - name: supervisor
      image: mr4x2/storm-supervisor-k8s
      ports:
        - containerPort: 6700
        - containerPort: 6701
        - containerPort: 6702
        - containerPort: 6703
      resources:
        limits:
          cpu: "4000m"  
          memory: "4Gi"