apiVersion: v1
kind: Pod
metadata:
  name: nimbus
  labels:
    app: nimbus
spec:
  containers:
    - name: nimbus
      image: mr4x2/storm-k8s
      ports:
        - containerPort: 8081
        - containerPort: 6627
      resources:
        limits:
          cpu: "1000m"  
          memory: "1Gi" 
