apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storm-cluster  # This should match the labels in the template
  template:
    metadata:
      labels:
        app: storm-cluster
    spec:
      containers:
        - name: nimbus
          image: mr4x2/storm-k8s
          ports:
            - containerPort: 8081
            - containerPort: 6627
          resources:
            limits:
              cpu: "1000m"  
              memory: "1Gi"
        - name: zookeeper
          image: mr4x2/zookeeper-k8s
          ports:
            - containerPort: 2181
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
        - name: supervisor
          image: mr4x2/storm-supervisor-k8s
          ports:
            - containerPort: 6700
            - containerPort: 6701
            - containerPort: 6702
            - containerPort: 6703
          resources:
            limits:
              cpu: "4000m"  
              memory: "4Gi"
