---
apiVersion: v1
kind: Service
metadata:
  namespace: storm-cluster
  name: zookeeper
spec:
  type: ClusterIP
  selector: 
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: nimbus-ui
  namespace: storm-cluster
spec:
  selector:
    app: nimbus
  type: NodePort  # Type set to NodePort for external access to 8081
  ports:
    - name: port-8081
      port: 8081         # Service port for external access
      targetPort: 8081   # Pod's containerPort for 8081
      nodePort: 30001    # NodePort for external access
---
apiVersion: v1
kind: Service
metadata:
  name: nimbus
  namespace: storm-cluster
spec:
  selector:
    app: nimbus
  type: ClusterIP  # Type set to ClusterIP for external access to 6627
  ports:
    - name: port-6627
      port: 6627         # Service port for internal access
      targetPort: 6627   # Pod's containerPort for 6627
---
apiVersion: v1
kind: Service
metadata:
  name: supervisor-dns
  namespace: storm-cluster
spec:
  clusterIP: None  # headless service
  selector:
    app: supervisor
  ports:
    - name: port-6700
      port: 6700
      targetPort: 6700
    - name: port-6701
      port: 6701
      targetPort: 6701
    - name: port-6702
      port: 6702
      targetPort: 6702
    - name: port-6703
      port: 6703
      targetPort: 6703
---
apiVersion: v1
kind: Service
metadata:
  namespace: storm-cluster
  name: mysql
spec:
  type: ClusterIP
  selector: 
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: storm-cluster
spec:
  type: NodePort
  selector:
    app: mqtt-broker
  ports:
    - name: port-1883
      port: 1883
      targetPort: 1883
      nodePort: 30002