apiVersion: v1
kind: Pod
metadata:
  name: supervisor
  labels:
    app: supervisor
spec:
  containers:
    - name: supervisor
      image: mr4x2/storm-supervisor-k8s
      ports:
        - containerPort: 6700
        - containerPort: 6701
        - containerPort: 6702
        - containerPort: 6703
      resources:
        limits:
          cpu: "4000m"  
          memory: "4Gi" 
