apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  selector:
    app: worker
  type: ClusterIP
  ports:
    - name: port-5672
      port: 5672
      targetPort: 5672