apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: storm-cluster
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - name: port-3000
      port: 3000
      targetPort: 3000
      nodePort: 30004