---
# tasks file for deploy
- name: Create storm ui
  community.docker.docker_container:
    name: storm-nimbus-ui
    image: mr4x2/nimbus:v2
    restart: true
    ports:
     - "6622:6627"
     - "8081:8081"
  tags: 
    - deploy_nimbus

- name: Create zookeeper
  community.docker.docker_container:
    name: zookeeper
    image: mr4x2/zookeeper:v1
    restart: true
    ports:
     - "2181:2181"
  tags: 
    - deploy_zookeeper

- name: Create supervisor
  community.docker.docker_container:
    name: storm-supervisor
    image: mr4x2/supervisor:v1
    restart: true
    ports:
     - "6700-6703:6700-6703"
  tags: 
    - deploy_supervisor