---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: storm-cluster
spec:
  type: NodePort
  selector:
    app: mqtt-broker
  ports:
    - name: port-1883
      port: 1883
      targetPort: 1883
      nodePort: 30002