---
apiVersion: v1
kind: Service
metadata:
  name: supervisor
  namespace: storm-cluster
spec:
  type: ClusterIP  # Internal access only
  selector:
    app: supervisor
  ports:
    - name: port-6700
      port: 6700
      targetPort: 6700
    - name: port-6701
      port: 6701
      targetPort: 6701
    - name: port-6702
      port: 6702
      targetPort: 6702
    - name: port-6703
      port: 6703
      targetPort: 6703