apiVersion: v1
kind: Service
metadata:
  name: nimbus
  namespace: storm-cluster
spec:
  selector:
    app: nimbus
  type: NodePort  # Type set to NodePort for external access to 8081
  ports:
    - name: port-8081
      port: 8081         # Service port for external access
      targetPort: 8081   # Pod's containerPort for 8081
      nodePort: 30001    # NodePort for external access
    - name: port-6627
      port: 6627         # Service port for internal access
      targetPort: 6627   # Pod's containerPort for 6627