apiVersion: v1
kind: Pod
metadata:
  name: nimbus
  namespace: storm-cluster
  labels:
    app: nimbus
spec:
  containers:
    - name: nimbus
      image: mr4x2/nimbus-k8s:v2
      ports:
        - containerPort: 8081
        - containerPort: 6627
      resources:
        limits:
          cpu: "1000m"  
          memory: "1Gi"
